services:
  database: 
    image: postgres:15
    container_name: strikeforce8

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin@2025
      - POSTGRES_DB=strikeforce_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d strikeforce_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:  