services:
  database: 
    image: postgres
    container_name: strikeforce88

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psotgres
      - POSTGRES_DB=postgres

    ports:
      - "5434:5432"